# Generated by Django 5.1.7 on 2026-02-06 12:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_counter', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('item_type', models.CharField(max_length=10)),
                ('item_category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('food_and_beverages', 'Food & Beverages'), ('fragile', 'Fragile Items'), ('books', 'Books'), ('others', 'Others')], default='other', max_length=50)),
                ('suggested_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('longitude', models.FloatField(default=7.0)),
                ('latitude', models.FloatField(default=7.0)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('idle_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_last_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('sent', 'Sent'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.offer')),
            ],
        ),
    ]
