# Generated by Django 5.1.7 on 2026-02-06 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='delivery.order'),
        ),
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.rider'),
        ),
        migrations.AddField(
            model_name='offer',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='delivery.rider'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['longitude', 'latitude'], name='delivery_ri_longitu_e05838_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['is_available', 'location_last_updated_at'], name='delivery_ri_is_avai_1eaead_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'rider', 'created_at'], name='delivery_or_custome_cc96ec_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['order', 'rider', 'created_at'], name='delivery_of_order_i_3fbb24_idx'),
        ),
    ]
