# Generated by Django 5.1.7 on 2025-07-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_order_accepted_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
