# Generated by Django 5.1.7 on 2025-07-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_driver_latitude_alter_driver_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=7.0),
        ),
    ]
