# Generated by Django 5.1.7 on 2025-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_driver_latitude_alter_driver_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=6.8),
        ),
    ]
