# Generated by Django 5.1.7 on 2025-08-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_driver_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=7.0),
        ),
    ]
