# Generated by Django 5.2.8 on 2025-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("documents", "Documents"),
                    ("clothing", "Clothing"),
                    ("food_&_beverages", "Food & Beverages"),
                    ("fragile_items", "Fragile Items"),
                    ("books", "Books"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
