# Generated by Django 5.1.7 on 2025-07-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_date_transaction_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transfer_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
