# Generated by Django 5.1.7 on 2025-07-14 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_account_number_wallet_transfer_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet'], name='wallet_tran_wallet__4da541_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'account_number'], name='wallet_wall_user_id_27e027_idx'),
        ),
    ]
