# Generated by Django 5.1.7 on 2025-07-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_wallet_tran_wallet__4da541_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_format',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer')], default='deposit', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transfer_pin',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
