# Generated by Django 5.1.7 on 2025-08-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_transaction_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
