# Generated by Django 5.1.7 on 2025-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transfer_pin',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
