# Generated by Django 4.2.17 on 2025-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='merchant_status',
            field=models.BooleanField(default=False),
        ),
    ]
