# Generated by Django 5.1.7 on 2025-07-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merchant_remove_customuser_merchant_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name': 'Merchant'},
        ),
    ]
