# Generated by Django 5.1.7 on 2025-07-12 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_options_alter_merchant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('phone_number', models.CharField(max_length=11)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile')),
                ('driver_license', models.ImageField(blank=True, upload_to='license')),
                ('bank_account', models.CharField(max_length=11)),
                ('bank', models.CharField(choices=[('access', 'Access Bank'), ('eco', 'Ecobank'), ('fcmb', 'FCMB'), ('fidelity', 'Fidelity Bank'), ('first', 'First Bank'), ('gtb', 'Guarantee Trust Bank'), ('heritage', 'Heritage Bank'), ('keystone', 'Keystone Bank'), ('polaris', 'Polaris Bank'), ('parallex', 'Parallex Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('union', 'Union Bank'), ('uba', 'United Bank of Africa'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank')], max_length=20)),
                ('plate_number', models.CharField(max_length=11)),
                ('brand_of_vehicle', models.CharField(max_length=15)),
                ('colour', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
