# Generated by Django 5.1.7 on 2025-07-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merchantprofile_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='home_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('merchant', 'MERCHANT')], default='customer', max_length=10),
        ),
    ]
