# Generated by Django 5.1.7 on 2025-07-16 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='user',
            field=models.OneToOneField(default=25, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
