# Generated by Django 5.1.7 on 2025-07-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merchantprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09012345678', max_length=11),
            preserve_default=False,
        ),
    ]
