# Generated by Django 5.1.7 on 2025-07-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_customerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MerchantProfile',
            new_name='DriverProfile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver')], default='customer', max_length=10),
        ),
    ]
