# Generated by Django 5.1.7 on 2026-02-06 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'IOS'), ('web', 'Web')], max_length=16)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
